version: '3.8'

services:
  svb-web:
    image: ljis120301/svb-web:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
      SMTP_HOST: 'mail.b.hostedemail.com'
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_USER: 'support@whoisjason.me'
      SMTP_PASS: 'Ilikepie120301!'
      EMAIL_FROM: 'support@whoisjason.me'
      SUPPORT_EMAIL: 'support@sunvalleybroadband.com'
      SALES_EMAIL: 'support@sunvalleybroadband.com'
      HCAPTCHA_SECRET: 'ES_403e7caa7d5d42a0a8019464e456941d'
      NEXT_PUBLIC_HCAPTCHA_SITEKEY: 'dbca6958-1bd6-4dcc-a0e0-b190e1b46d4e'
      NEXT_PUBLIC_GA_ID: 'G-LVPSHQM46D'

    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
